<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.14">
  <compounddef id="classpysc2_1_1lib_1_1remote__controller_1_1_connect_error" kind="class" language="Python" prot="public">
    <compoundname>pysc2::lib::remote_controller::ConnectError</compoundname>
    <basecompoundref prot="public" virt="non-virtual">Exception</basecompoundref>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="180">
        <label>Exception</label>
      </node>
      <node id="179">
        <label>pysc2.lib.remote_controller.ConnectError</label>
        <link refid="classpysc2_1_1lib_1_1remote__controller_1_1_connect_error"/>
        <childnode refid="180" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="182">
        <label>Exception</label>
      </node>
      <node id="181">
        <label>pysc2.lib.remote_controller.ConnectError</label>
        <link refid="classpysc2_1_1lib_1_1remote__controller_1_1_connect_error"/>
        <childnode refid="182" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="lib/remote_controller.py" line="37" column="1" bodyfile="lib/remote_controller.py" bodystart="37" bodyend="41"/>
    <listofallmembers>
    </listofallmembers>
  </compounddef>
</doxygen>
